// src/materials/materialLibrary.ts
import type { Material, MaterialCategory } from './types';

export const materialLibrary: Material[] = [
  // === WOOD FLOORS (10 species) ===
  {
    id: 'wood_red_oak',
    name: 'Red Oak',
    category: 'floor',
    subcategory: 'wood',
    color: '#984A2B',
    colorSecondary: '#B86B4A',
    roughness: 0.7,
    metalness: 0,
    pattern: 'herringbone',
    woodSpecies: 'red_oak',
    woodCut: 'plain_sawn',
    woodFinish: 'satin',
  },
  {
    id: 'wood_white_oak',
    name: 'White Oak',
    category: 'floor',
    subcategory: 'wood',
    color: '#C9A86C',
    colorSecondary: '#D4B896',
    roughness: 0.65,
    metalness: 0,
    pattern: 'parquet',
    woodSpecies: 'white_oak',
    woodCut: 'quarter_sawn',
    woodFinish: 'satin',
  },
  {
    id: 'wood_walnut',
    name: 'Black Walnut',
    category: 'floor',
    subcategory: 'wood',
    color: '#5C4033',
    colorSecondary: '#6B4423',
    roughness: 0.6,
    metalness: 0,
    pattern: 'strip',
    woodSpecies: 'walnut',
    woodCut: 'rift_sawn',
    woodFinish: 'semi_gloss',
  },
  {
    id: 'wood_maple',
    name: 'Hard Maple',
    category: 'floor',
    subcategory: 'wood',
    color: '#C4A882',
    colorSecondary: '#E8D9B5',
    roughness: 0.65,
    metalness: 0,
    pattern: 'strip',
    woodSpecies: 'maple',
    woodFinish: 'satin',
  },
  {
    id: 'wood_cherry',
    name: 'Cherry',
    category: 'floor',
    subcategory: 'wood',
    color: '#9B4F34',
    colorSecondary: '#B87333',
    roughness: 0.55,
    metalness: 0,
    pattern: 'parquet',
    woodSpecies: 'cherry',
    woodFinish: 'semi_gloss',
  },
  {
    id: 'wood_mahogany',
    name: 'Mahogany',
    category: 'floor',
    subcategory: 'wood',
    color: '#8B4513',
    colorSecondary: '#D4A574',
    roughness: 0.5,
    metalness: 0,
    pattern: 'herringbone',
    woodSpecies: 'mahogany',
    woodCut: 'quarter_sawn',
    woodFinish: 'glossy',
  },
  {
    id: 'wood_teak',
    name: 'Teak',
    category: 'floor',
    subcategory: 'wood',
    color: '#B8860B',
    colorSecondary: '#CD853F',
    roughness: 0.6,
    metalness: 0.05,
    pattern: 'strip',
    woodSpecies: 'teak',
    woodFinish: 'satin',
  },
  {
    id: 'wood_ash',
    name: 'Ash',
    category: 'floor',
    subcategory: 'wood',
    color: '#E8D9B5',
    colorSecondary: '#C4A882',
    roughness: 0.7,
    metalness: 0,
    pattern: 'herringbone',
    woodSpecies: 'ash',
    woodFinish: 'matte',
  },
  {
    id: 'wood_hickory',
    name: 'Hickory',
    category: 'floor',
    subcategory: 'wood',
    color: '#E8D9B5',
    colorSecondary: '#8B7355',
    roughness: 0.8,
    metalness: 0,
    pattern: 'strip',
    woodSpecies: 'hickory',
    woodFinish: 'matte',
  },
  {
    id: 'wood_pine',
    name: 'Pine',
    category: 'floor',
    subcategory: 'wood',
    color: '#F5ECD7',
    colorSecondary: '#CD853F',
    roughness: 0.75,
    metalness: 0,
    pattern: 'solid',
    woodSpecies: 'pine',
    woodCut: 'plain_sawn',
    woodFinish: 'matte',
  },

  // === STONE (8 types) ===
  {
    id: 'stone_granite',
    name: 'Granite',
    category: 'floor',
    subcategory: 'stone',
    color: '#B8B8B8',
    colorSecondary: '#8A8A8A',
    roughness: 0.3,
    metalness: 0.1,
    pattern: 'solid',
    stoneType: 'granite',
    stoneFinish: 'polished',
  },
  {
    id: 'stone_marble',
    name: 'Marble',
    category: 'floor',
    subcategory: 'stone',
    color: '#F0EDE8',
    colorSecondary: '#D0C8C0',
    roughness: 0.2,
    metalness: 0.05,
    pattern: 'solid',
    stoneType: 'marble',
    stoneFinish: 'polished',
  },
  {
    id: 'stone_limestone',
    name: 'Limestone',
    category: 'floor',
    subcategory: 'stone',
    color: '#D4C4A8',
    colorSecondary: '#A89070',
    roughness: 0.6,
    metalness: 0,
    pattern: 'solid',
    stoneType: 'limestone',
    stoneFinish: 'honed',
  },
  {
    id: 'stone_slate',
    name: 'Slate',
    category: 'floor',
    subcategory: 'stone',
    color: '#5A5A5A',
    colorSecondary: '#3A3A3A',
    roughness: 0.5,
    metalness: 0,
    pattern: 'grid',
    stoneType: 'slate',
    stoneFinish: 'natural_cleft',
  },
  {
    id: 'stone_travertine',
    name: 'Travertine',
    category: 'floor',
    subcategory: 'stone',
    color: '#E8D9B5',
    colorSecondary: '#C4A882',
    roughness: 0.45,
    metalness: 0,
    pattern: 'solid',
    stoneType: 'travertine',
    stoneFinish: 'tumbled',
  },
  {
    id: 'stone_quartzite',
    name: 'Quartzite',
    category: 'floor',
    subcategory: 'stone',
    color: '#E8E8E0',
    colorSecondary: '#C8C8C0',
    roughness: 0.25,
    metalness: 0.1,
    pattern: 'solid',
    stoneType: 'quartzite',
    stoneFinish: 'polished',
  },
  {
    id: 'stone_onyx',
    name: 'Onyx',
    category: 'floor',
    subcategory: 'stone',
    color: '#1A1A1A',
    colorSecondary: '#3A3A3A',
    roughness: 0.1,
    metalness: 0.05,
    pattern: 'solid',
    stoneType: 'onyx',
    stoneFinish: 'polished',
  },
  {
    id: 'stone_sandstone',
    name: 'Sandstone',
    category: 'floor',
    subcategory: 'stone',
    color: '#D4A574',
    colorSecondary: '#A67B5B',
    roughness: 0.65,
    metalness: 0,
    pattern: 'solid',
    stoneType: 'sandstone',
    stoneFinish: 'natural_cleft',
  },

  // === TILE (5 types) ===
  {
    id: 'tile_ceramic',
    name: 'Ceramic Tile',
    category: 'floor',
    subcategory: 'tile',
    color: '#E8E0D8',
    roughness: 0.4,
    metalness: 0,
    pattern: 'grid',
    tileType: 'ceramic',
    tileSize: '12x12',
  },
  {
    id: 'tile_porcelain',
    name: 'Porcelain Tile',
    category: 'floor',
    subcategory: 'tile',
    color: '#D8D0C8',
    roughness: 0.2,
    metalness: 0.05,
    pattern: 'grid',
    tileType: 'porcelain',
    tileSize: '24x24',
  },
  {
    id: 'tile_terracotta',
    name: 'Terracotta',
    category: 'floor',
    subcategory: 'tile',
    color: '#C47840',
    colorSecondary: '#A86030',
    roughness: 0.7,
    metalness: 0,
    pattern: 'solid',
    tileType: 'terracotta',
    tileSize: '8x8',
  },
  {
    id: 'tile_cement',
    name: 'Cement Tile',
    category: 'floor',
    subcategory: 'tile',
    color: '#9A9590',
    roughness: 0.5,
    metalness: 0,
    pattern: 'grid',
    tileType: 'cement',
    tileSize: '8x8',
  },
  {
    id: 'tile_mosaic',
    name: 'Mosaic',
    category: 'floor',
    subcategory: 'tile',
    color: '#C8C8C8',
    roughness: 0.3,
    metalness: 0.1,
    pattern: 'grid',
    tileType: 'mosaic',
    tileSize: '2x2',
  },

  // === CONCRETE FLOORS ===
  {
    id: 'floor_concrete',
    name: 'Concrete',
    category: 'floor',
    subcategory: 'concrete',
    color: '#808080',
    roughness: 0.85,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'floor_polished_concrete',
    name: 'Polished Concrete',
    category: 'floor',
    subcategory: 'concrete',
    color: '#909090',
    roughness: 0.3,
    metalness: 0.05,
    pattern: 'solid',
  },

  // === CARPET ===
  {
    id: 'floor_carpet',
    name: 'Carpet',
    category: 'floor',
    subcategory: 'fabric',
    color: '#6A5A7A',
    roughness: 0.95,
    metalness: 0,
    pattern: 'solid',
  },

  // === VINYL / LAMINATE ===
  {
    id: 'floor_vinyl',
    name: 'Vinyl',
    category: 'floor',
    subcategory: 'synthetic',
    color: '#908070',
    roughness: 0.4,
    metalness: 0,
    pattern: 'strip',
  },
  {
    id: 'floor_laminate',
    name: 'Laminate',
    category: 'floor',
    subcategory: 'synthetic',
    color: '#B89060',
    roughness: 0.5,
    metalness: 0,
    pattern: 'strip',
  },

  // === WALL MATERIALS (8) ===
  {
    id: 'wall_drywall',
    name: 'Drywall',
    category: 'wall',
    subcategory: 'plaster',
    color: '#F0EDE8',
    roughness: 0.9,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'wall_exposed_brick',
    name: 'Exposed Brick',
    category: 'wall',
    subcategory: 'brick',
    color: '#8B4513',
    roughness: 0.85,
    metalness: 0,
    pattern: 'grid',
  },
  {
    id: 'wall_stone',
    name: 'Stone',
    category: 'wall',
    subcategory: 'stone',
    color: '#706860',
    roughness: 0.7,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'wall_marble',
    name: 'Marble',
    category: 'wall',
    subcategory: 'stone',
    color: '#F5F5F0',
    colorSecondary: '#D0C8C0',
    roughness: 0.2,
    metalness: 0.05,
    pattern: 'solid',
  },
  {
    id: 'wall_subway_tile',
    name: 'Subway Tile',
    category: 'wall',
    subcategory: 'tile',
    color: '#E8E0D8',
    roughness: 0.3,
    metalness: 0,
    pattern: 'grid',
  },
  {
    id: 'wall_plaster',
    name: 'Plaster',
    category: 'wall',
    subcategory: 'plaster',
    color: '#F5EDE0',
    roughness: 0.85,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'wall_concrete',
    name: 'Concrete',
    category: 'wall',
    subcategory: 'concrete',
    color: '#707070',
    roughness: 0.8,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'wall_wood',
    name: 'Wood Paneling',
    category: 'wall',
    subcategory: 'wood',
    color: '#9E7040',
    roughness: 0.6,
    metalness: 0,
    pattern: 'strip',
  },

  // === CEILING MATERIALS (6) ===
  {
    id: 'ceiling_flat',
    name: 'Flat White',
    category: 'ceiling',
    color: '#F0EDE8',
    roughness: 0.95,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'ceiling_coffered',
    name: 'Coffered',
    category: 'ceiling',
    color: '#E8E0D8',
    roughness: 0.8,
    metalness: 0,
    pattern: 'grid',
  },
  {
    id: 'ceiling_vaulted',
    name: 'Vaulted',
    category: 'ceiling',
    color: '#E0D8D0',
    roughness: 0.7,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'ceiling_beam_exposed',
    name: 'Exposed Beams',
    category: 'ceiling',
    color: '#8B6040',
    roughness: 0.7,
    metalness: 0,
    pattern: 'strip',
  },
  {
    id: 'ceiling_plaster',
    name: 'Plaster',
    category: 'ceiling',
    color: '#F5F0E8',
    roughness: 0.85,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'ceiling_tin',
    name: 'Tin',
    category: 'ceiling',
    color: '#A0A0A0',
    roughness: 0.4,
    metalness: 0.7,
    pattern: 'grid',
  },

  // === ROOF MATERIALS (5) ===
  {
    id: 'roof_asphalt_shingle',
    name: 'Asphalt Shingle',
    category: 'roof',
    color: '#4A4A4A',
    roughness: 0.85,
    metalness: 0,
    pattern: 'grid',
  },
  {
    id: 'roof_clay_tile',
    name: 'Clay Tile',
    category: 'roof',
    color: '#C47840',
    roughness: 0.7,
    metalness: 0,
    pattern: 'grid',
  },
  {
    id: 'roof_metal',
    name: 'Metal Roof',
    category: 'roof',
    color: '#808080',
    roughness: 0.4,
    metalness: 0.8,
    pattern: 'strip',
  },
  {
    id: 'roof_membrane',
    name: 'Membrane',
    category: 'roof',
    color: '#606060',
    roughness: 0.6,
    metalness: 0.1,
    pattern: 'solid',
  },
  {
    id: 'roof_cedar_shake',
    name: 'Cedar Shake',
    category: 'roof',
    color: '#8B6040',
    roughness: 0.8,
    metalness: 0,
    pattern: 'grid',
  },

  // === FURNITURE MATERIALS (7 fabric) ===
  {
    id: 'fabric_cotton',
    name: 'Cotton Fabric',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#C8B8A8',
    roughness: 0.95,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'fabric_leather',
    name: 'Leather',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#5C3A1E',
    roughness: 0.5,
    metalness: 0.05,
    pattern: 'solid',
  },
  {
    id: 'fabric_velvet',
    name: 'Velvet',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#4A3A6A',
    roughness: 0.9,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'fabric_linen',
    name: 'Linen',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#D4C8B0',
    roughness: 0.9,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'fabric_microfiber',
    name: 'Microfiber',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#9A9590',
    roughness: 0.85,
    metalness: 0,
    pattern: 'solid',
  },
  {
    id: 'fabric_silk',
    name: 'Silk',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#E8D8C8',
    roughness: 0.3,
    metalness: 0.1,
    pattern: 'solid',
  },
  {
    id: 'fabric_wool',
    name: 'Wool',
    category: 'furniture',
    subcategory: 'fabric',
    color: '#8B7355',
    roughness: 0.9,
    metalness: 0,
    pattern: 'solid',
  },
];

export function getMaterial(id: string): Material | undefined {
  return materialLibrary.find(m => m.id === id);
}

export function getMaterialsByCategory(category: MaterialCategory): Material[] {
  return materialLibrary.filter(m => m.category === category);
}

export function getMaterialsBySubcategory(subcategory: string): Material[] {
  return materialLibrary.filter(m => m.subcategory === subcategory);
}
